/* tslint:disable */
/* eslint-disable */
/**
 * OpenApiSample
 * This is documentation of OpenApiSample
 *
 * The version of the OpenAPI document: v1.0.0
 * Contact: info@arturdr.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum Sex {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}

export function SexFromJSON(json: any): Sex {
    return SexFromJSONTyped(json, false);
}

export function SexFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sex {
    return json as Sex;
}

export function SexToJSON(value?: Sex | null): any {
    return value as any;
}

