// tslint:disable
/**
 * OpenApiSample
 * This is documentation of OpenApiSample
 *
 * The version of the OpenAPI document: v1.0.0
 * Contact: info@arturdr.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
